---
title: "STAT 380 Kunal"
output: html_notebook
---

# Libraries 
```{r}
library(ggplot2)
library(dplyr)
library(boot)       # bootstrap
library(car)
library(ISLR2)
library(caret)
library(glmnet)
library(leaps)




beta0 <- 1
beta1 <- 10
sigma <- 40
n <- 100
x <- rnorm(n,50,5)
y <- rnorm(n,beta0 + beta1*x, sigma)
plot(x,y, pch = 16, col = 4)


fit <- lm(y ~ x)
resid(fit)
b <- coef(fit)
resi <- y - (b[1] + b[2] * x)
resi
resid(fit$coefficients)^2
```


**Krish Section**


```{r}
# Example for SLR with Danceability, Energy, Valence
slr_model_Danceability <- lm(Popularity ~ Danceability, data = SpotifyDataset)
slr_model_Valence <- lm(Popularity ~ Valence, data = SpotifyDataset)
slr_model_Loudness <- lm(Popularity ~ Loudness, data = SpotifyDataset)
slr_model_Liveness <- lm(Popularity ~ Liveness, data = SpotifyDataset)
slr_model_Time.Signature <- lm(Popularity ~ Time.Signature, data = SpotifyDataset)
#slr_model_Genres <- glm(Popularity ~ Artist.Genres, data = SpotifyDataset)
# Example for MLR with multiple variables
mlr_model <- lm(Popularity ~ Danceability + Loudness + Valence + Liveness + Time.Signature, data = SpotifyDataset)

summary(slr_model_Danceability)
summary(slr_model_Valence)
summary(slr_model_Loudness)
summary(slr_model_Liveness)
summary(slr_model_Time.Signature)
#summary(slr_model_Genres)
summary(mlr_model)
plot(slr_model_Danceability)
plot(slr_model_Valence)
plot(slr_model_Loudness)
plot(slr_model_Liveness)
plot(slr_model_Time.Signature)
plot(mlr_model)

# R-squared and Adjusted R-squared
cat("R-squared:", summary(mlr_model)$r.squared, "\n")
cat("Adjusted R-squared:", summary(mlr_model)$adj.r.squared, "\n")

# F-statistic
cat("F-statistic:", summary(mlr_model)$fstatistic[1], "\n")
cat("p-value:", pf(summary(mlr_model)$fstatistic[1], summary(mlr_model)$fstatistic[2], summary(mlr_model)$fstatistic[3], lower.tail = FALSE), "\n")

# Assuming SpotifyDataset is your dataset
correlation_matrix <- cor(SpotifyDataset[, c("Danceability", "Energy", "Valence", "Loudness", "Liveness", "Tempo", "Time.Signature", "Popularity")])

# Print the correlation matrix
print(correlation_matrix)

# Install and load reshape2 package
install.packages("reshape2")
library(reshape2)

# Assuming SpotifyDataset is your dataset
correlation_matrix <- cor(SpotifyDataset[, c("Danceability", "Energy", "Valence", "Loudness", "Liveness", "Tempo", "Time.Signature", "Popularity")])

# Print the correlation matrix
print(correlation_matrix)

# Plot a heatmap of the correlation matrix
library(ggplot2)
ggplot(data = melt(correlation_matrix), aes(Var1, Var2, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1), space = "Lab") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1))

```


```{r}
mlr_model1 <- lm(Popularity ~ Mode + Loudness + Speechiness + Instrumentalness + Acousticness + Time.Signature + Tempo, data = SpotifyDataset)



mlr_2 <- lm(Popularity ~ Energy + Loudness + Liveness + Valence, data = SpotifyDataset)


summary(mlr_model1)
avPlots(mlr_model1)



model_residuals1 = mlr_model$residuals

# Plot the result
hist(model_residuals1)

qqnorm(model_residuals1)
# Plot the Q-Q line
qqline(model_residuals1)


summary(mlr_2)

model_residuals2 = mlr_2$residuals

# Plot the result
hist(model_residuals2)

qqnorm(model_residuals2)
# Plot the Q-Q line
qqline(model_residuals2)



anova(mlr_2,mlr_model1)

```


# Dataset
```{r}
SpotifyDataset <- read.csv(file = "SpotifyDataset.csv", stringsAsFactors = FALSE)

# Edit this to the columns we want to use
SpotifyDataset <- SpotifyDataset%>%
  select(-Track.URI, -Artist.URI.s. , -Album.URI, -Album.Artist.URI.s. , -Album.Image.URL , -Track.Preview.URL , -ISRC, -Added.By, -Added.At, -Album.Genres, -Copyrights)

SpotifyDataset
```


```{r}
SpotifyRegfit.fwd = regsubsets(Popularity ~. , data=SpotifyDataset, nvmax=10, method ="exhaustive")
summary(SpotifyRegfit.fwd)


SpotifyReg.summary <- summary(SpotifyRegfit.fwd) #get the summary



#adjr2 plot
plot(SpotifyReg.summary$adjr2 ,xlab="Number of Variables ", ylab="Adjusted RSq",type="l")
SpotifyMax_adjr2 <- which.max(SpotifyReg.summary$adjr2)
points(SpotifyMax_adjr2,SpotifyReg.summary$adjr2[Spotifymax_adjr2], col="red",cex=2,pch=20)

# AIC criterion (Cp) to minimize
plot(SpotifyReg.summary$cp ,xlab="Number of Variables ",ylab="Cp", type='l')
SpotifyMin_cp <- which.min(SpotifyReg.summary$cp )
points(SpotifyMin_cp, SpotifyReg.summary$cp[SpotifyMin_cp],col="red",cex=2,pch=20)

# BIC criterion to minimize
plot(SpotifyReg.summary$bic ,xlab="Number of Variables ",ylab="BIC",type='l')
SpotifyMin_bic <- which.min(SpotifyReg.summary$bic)
points(SpotifyMin_bic,SpotifyReg.summary$bic[SpotifyMin_bic],col="red",cex=2,pch=20)
```



```{r}


x_var <- SpotifyDataset %>% select(-Popularity) %>% as.matrix() %>% na.omit
# getting the independent variable
y_var <- SpotifyDataset[,"Popularity"] 


lasso <- glmnet(x_var, y_var, alpha=1)
summary(lasso)


min_lasso <- glmnet(x_var, y_var, alpha=1, lambda = lasso$lambda.min)

predictions.lasso <- min_lasso %>% predict(x_var) %>% as.vector()
# Model performance metrics
data.frame(
  MSE = (RMSE(predictions.lasso, y_var))^2,
  Rsquare = R2(predictions.lasso, y_var)
)

```










```{r}

Spotify_boot <- SpotifyDataset %>% 

  slice_sample(n = 1000, replace = FALSE) 

  

summary(Spotify_boot)

``` 


```{r}
ggplot(Spotify_boot, aes(x=Valence, y=Popularity)) + 
    geom_point()
```









 
```{r}
library(mosaic)
fav_stats(Spotify_boot$Popularity)
```



```{r}


mean.function <- function(x, index) {
  d <- x[index]     # This first line will go in ever bootstrap function you make.
  return(mean(d))  
}
DanceBootDist <- boot(data = SpotifyDataset$Danceability, statistic = mean.function, R=10000)

DanceBootDist.graph <- data.frame(xbar=DanceBootDist$t)
ggplot(DanceBootDist.graph, aes(x=xbar)) +
  geom_histogram() + 
  ggtitle('Estimated Sampling distribution of Dancebility' )

```





```{r}
ValenceBootDist <- boot(data = SpotifyDataset$Valence, statistic = mean.function, R=10000)

ValenceBootDist.graph <- data.frame(xbar=ValenceBootDist$t)
ggplot(ValenceBootDist.graph, aes(x=xbar)) +
  geom_histogram(fill = 'green') + 
  ggtitle('Estimated Sampling distribution of Valence' )
```
We can conclude that majority of the music on Spotify envokes positive feelings 




By genre:

```{r}
by_genre <- function(data, genres, pop) {
  unique <- unique(data[[genres]])
  
  for (genre in unique) {
    genre_data <- data[data[[genres]] == genre, ]
    
  }
}


Spotify.genre <- by_genre(SpotifyDataset, "Genre", "Popularity")

Spotify.genre
```



