---
title: "STAT 380 Maggie"
output: html_notebook
---

Libraries 
```{r}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(mdsr)
library(mvtnorm)
library(factoextra)
```

# Dataset
```{r}
SpotifyDataset <- read.csv(file = "SpotifyDataset.csv", stringsAsFactors = FALSE)

# Edit this to the columns we want to use
SpotifyDataset <- SpotifyDataset%>%
  select(-Track.URI, -Artist.URI.s. , -Album.URI, -Album.Artist.URI.s. , -Album.Image.URL , -Track.Preview.URL , -ISRC, -Added.By, -Added.At, -Album.Genres, -Copyrights)

# remove cases with missing data
SpotifyDataset <- na.omit(SpotifyDataset)

SpotifyDataset
```

```{r}
# create new dataset with only numeric variables for pca
NumSpotifyDataset <-
  SpotifyDataset %>%
  select(-Popularity, -Track.Name, -Artist.Name.s., -Album.Name, -Album.Artist.Name.s., -Album.Release.Date, -Disc.Number, -Track.Number, -Track.Duration..ms., -Explicit, -Artist.Genres, -Time.Signature, -Label)

NumSpotifyDataset
```

```{r}
# perform pca, being sure to scale the variables
princomp <-
NumSpotifyDataset %>%
  prcomp(scale = TRUE)
princomp
```

```{r}
# eigenvalue, PVE and cumulative PVE for each PC
pve <- get_eig(princomp)
pve

# scree plot to find the "elbow"
fviz_screeplot(princomp, main = "Scree Plot for SpotifyDataset")

# scree plot to find how many components must be included for at least 80% of variance to be explained
pve %>%
  ggplot(aes(x = 1:11, y = cumulative.variance.percent)) + 
  geom_line() + 
  geom_point() +
  geom_hline(yintercept = 80) +
  xlab("Dimension") +
  ylab("Cumulative Variance Explained") +
  ggtitle("Cumulative Variance Explained With Each Principle Component in SpotifyDataset")
```

```{r}
# create a matrix using the first 7 components
score_mat <- princomp$x
sel_pcs <- 1:7
score_mat2 <- score_mat[,sel_pcs]
score_mat2
```

```{r}
#dataframe with each song's popularity score and components
PCASpotify <- data.frame(SpotifyDataset$Popularity, score_mat2)
```

```{r}
cor_matrix <- function(X){
  for(i in 1:ncol(X)){
    if(is.numeric(X[,i])){
      print(X %>%
      ggplot(aes(x=X[,i], y=SpotifyDataset.Popularity)) + geom_point() + geom_smooth(method="lm") + xlab(names(X)[i]) + ylab("Popularity"))
    }
  }
}
cor_matrix(PCASpotify)
```



